export const countries = {
  Afeganistão: "Afeganistão",
  "África do Sul": "África do Sul",
  Albânia: "Albânia",
  Alemanha: "Alemanha",
  Andorra: "Andorra",
  Angola: "Angola",
  Anguilla: "Anguilla",
  Antártica: "Antártica",
  "Antígua e Barbuda": "Antígua e Barbuda",
  "Arábia Saudita": "Arábia Saudita",
  Argélia: "Argélia",
  Argentina: "Argentina",
  Armênia: "Armênia",
  Aruba: "Aruba",
  Austrália: "Austrália",
  Áustria: "Áustria",
  Azerbaijão: "Azerbaijão",
  Bahamas: "Bahamas",
  Bangladesh: "Bangladesh",
  Barbados: "Barbados",
  Barém: "Barém",
  Belarus: "Belarus",
  Bélgica: "Bélgica",
  Belize: "Belize",
  Benin: "Benin",
  Bermuda: "Bermuda",
  Birmânia: "Birmânia",
  Bolívia: "Bolívia",
  "Bósnia e Herzegovina": "Bósnia e Herzegovina",
  Botswana: "Botswana",
  Brasil: "Brasil",
  Brunei: "Brunei",
  Bulgária: "Bulgária",
  "Burkina Faso": "Burkina Faso",
  Burundi: "Burundi",
  Butão: "Butão",
  "Cabo Verde": "Cabo Verde",
  Camarões: "Camarões",
  Camboja: "Camboja",
  Canadá: "Canadá",
  Cazaquistão: "Cazaquistão",
  Chad: "Chad",
  Chile: "Chile",
  China: "China",
  Chipre: "Chipre",
  Cingapura: "Cingapura",
  Cisjordânia: "Cisjordânia",
  Colômbia: "Colômbia",
  Cômoros: "Cômoros",
  "Coreia do Norte": "Coreia do Norte",
  "Coreia do Sul": "Coreia do Sul",
  "Costa do Marfim": "Costa do Marfim",
  "Costa Rica": "Costa Rica",
  Croácia: "Croácia",
  Cuba: "Cuba",
  Curaçao: "Curaçao",
  Dinamarca: "Dinamarca",
  Djibuti: "Djibuti",
  Dominica: "Dominica",
  Egito: "Egito",
  "El Salvador": "El Salvador",
  "Emirados Árabes Unidos": "Emirados Árabes Unidos",
  Equador: "Equador",
  Eritréia: "Eritréia",
  Eslováquia: "Eslováquia",
  Eslovênia: "Eslovênia",
  Espanha: "Espanha",
  "Estados Unidos": "Estados Unidos",
  Estônia: "Estônia",
  Etiópia: "Etiópia",
  "Faixa de Gaza": "Faixa de Gaza",
  Fiji: "Fiji",
  Filipinas: "Filipinas",
  Finlândia: "Finlândia",
  "França Metropolitana": "França Metropolitana",
  França: "França",
  Gabão: "Gabão",
  Gâmbia: "Gâmbia",
  Gana: "Gana",
  "Geórgia do Sul e Ilhas": "Geórgia do Sul e Ilhas",
  Geórgia: "Geórgia",
  Gibraltar: "Gibraltar",
  Grécia: "Grécia",
  Greenland: "Greenland",
  Grenada: "Grenada",
  Guadelupe: "Guadelupe",
  Guam: "Guam",
  Guatemala: "Guatemala",
  Guernsey: "Guernsey",
  "Guiana Francesa": "Guiana Francesa",
  Guiana: "Guiana",
  "Guiné Equatorial": "Guiné Equatorial",
  Guiné: "Guiné",
  "Guiné-Bissau": "Guiné-Bissau",
  Haiti: "Haiti",
  Holanda: "Holanda",
  Honduras: "Honduras",
  "Hong Kong": "Hong Kong",
  Hungria: "Hungria",
  Iêmen: "Iêmen",
  "Ilha Bouvet": "Ilha Bouvet",
  "Ilha Christmas": "Ilha Christmas",
  "Ilha de Man": "Ilha de Man",
  "Ilha Norfolk": "Ilha Norfolk",
  "Ilhas Caiman": "Ilhas Caiman",
  "Ilhas Cocos (Keeling)": "Ilhas Cocos (Keeling)",
  "Ilhas Cook": "Ilhas Cook",
  "Ilhas Falkland (Malvinas)": "Ilhas Falkland (Malvinas)",
  "Ilhas Feroe": "Ilhas Feroe",
  "Ilhas Heard and McDonald": "Ilhas Heard and McDonald",
  "Ilhas Marianas do Norte": "Ilhas Marianas do Norte",
  "Ilhas Marshall": "Ilhas Marshall",
  "Ilhas Maurício": "Ilhas Maurício",
  "Ilhas Menores Distantes dos Estados Unidos":
    "Ilhas Menores Distantes dos Estados Unidos",
  "Ilhas Pitcairn": "Ilhas Pitcairn",
  "Ilhas Salomão": "Ilhas Salomão",
  "Ilhas Turks e Caicos": "Ilhas Turks e Caicos",
  "Ilhas Virgens Americanas": "Ilhas Virgens Americanas",
  "Ilhas Virgens Britânicas": "Ilhas Virgens Britânicas",
  "Ilhas Wallis e Futuna": "Ilhas Wallis e Futuna",
  Índia: "Índia",
  Indonésia: "Indonésia",
  Irã: "Irã",
  Iraque: "Iraque",
  Irlanda: "Irlanda",
  Islândia: "Islândia",
  Israel: "Israel",
  Itália: "Itália",
  Jamaica: "Jamaica",
  Japão: "Japão",
  Jersey: "Jersey",
  Jordânia: "Jordânia",
  Kiribati: "Kiribati",
  Kosovo: "Kosovo",
  Kuwait: "Kuwait",
  Laos: "Laos",
  Lesoto: "Lesoto",
  Letônia: "Letônia",
  Líbano: "Líbano",
  Libéria: "Libéria",
  Líbia: "Líbia",
  Liechtenstein: "Liechtenstein",
  Lituânia: "Lituânia",
  Luxemburgo: "Luxemburgo",
  Macao: "Macao",
  Macedônia: "Macedônia",
  Madagascar: "Madagascar",
  Maiote: "Maiote",
  Malásia: "Malásia",
  Malawi: "Malawi",
  Maldivas: "Maldivas",
  Mali: "Mali",
  Malta: "Malta",
  Marrocos: "Marrocos",
  Martinica: "Martinica",
  Mauritânia: "Mauritânia",
  México: "México",
  "Micronésia, Estados Federados da": "Micronésia, Estados Federados da",
  Moçambique: "Moçambique",
  Moldova: "Moldova",
  Mônaco: "Mônaco",
  Mongólia: "Mongólia",
  Montenegro: "Montenegro",
  Montserrat: "Montserrat",
  Namíbia: "Namíbia",
  Nauru: "Nauru",
  Nepal: "Nepal",
  Nicarágua: "Nicarágua",
  Níger: "Níger",
  Nigéria: "Nigéria",
  Niue: "Niue",
  Noruega: "Noruega",
  "Nova Caledônia": "Nova Caledônia",
  "Nova Zelândia": "Nova Zelândia",
  Omã: "Omã",
  Outros: "Outros",
  Palau: "Palau",
  Panamá: "Panamá",
  "Papua Nova Guiné": "Papua Nova Guiné",
  Paquistão: "Paquistão",
  Paraguai: "Paraguai",
  Peru: "Peru",
  "Polinésia Francesa": "Polinésia Francesa",
  Polônia: "Polônia",
  "Porto Rico": "Porto Rico",
  Portugal: "Portugal",
  Qatar: "Qatar",
  Quênia: "Quênia",
  Quirguistão: "Quirguistão",
  "Reino Unido": "Reino Unido",
  "República Centro-Africana": "República Centro-Africana",
  "República Democrática do Congo": "República Democrática do Congo",
  "República do Congo": "República do Congo",
  "República Dominicana": "República Dominicana",
  "República Tcheca": "República Tcheca",
  Reunião: "Reunião",
  Romênia: "Romênia",
  Ruanda: "Ruanda",
  Rússia: "Rússia",
  "Saara Ocidental": "Saara Ocidental",
  "Saint Martin": "Saint Martin",
  "Saint Pierre e Miquelon": "Saint Pierre e Miquelon",
  "Samoa Americana": "Samoa Americana",
  Samoa: "Samoa",
  "San Marino": "San Marino",
  "Santa Helena, Ascensão e Tristão da Cunha":
    "Santa Helena, Ascensão e Tristão da Cunha",
  "Santa Lúcia": "Santa Lúcia",
  "Santa Sé (Cidade do Vaticano)": "Santa Sé (Cidade do Vaticano)",
  "São Bartolomeu": "São Bartolomeu",
  "São Cristóvão e Nevis": "São Cristóvão e Nevis",
  "São Martinho": "São Martinho",
  "São Tomé e Príncipe": "São Tomé e Príncipe",
  "São Vicente e Granadinas": "São Vicente e Granadinas",
  Seicheles: "Seicheles",
  Senegal: "Senegal",
  "Serra Leoa": "Serra Leoa",
  Sérvia: "Sérvia",
  Síria: "Síria",
  Somália: "Somália",
  "Sri Lanka": "Sri Lanka",
  Suazilândia: "Suazilândia",
  "Sudão do Sul": "Sudão do Sul",
  Sudão: "Sudão",
  Suécia: "Suécia",
  Suíça: "Suíça",
  "Sul da França e Antártica": "Sul da França e Antártica",
  Suriname: "Suriname",
  Svalbard: "Svalbard",
  Tadjiquistão: "Tadjiquistão",
  Tailândia: "Tailândia",
  Taiwan: "Taiwan",
  Tanzânia: "Tanzânia",
  "Território Britânico do Oceano Índico":
    "Território Britânico do Oceano Índico",
  "Timor-Leste": "Timor-Leste",
  Togo: "Togo",
  Tonga: "Tonga",
  Toquelau: "Toquelau",
  "Trinidad e Tobago": "Trinidad e Tobago",
  Tunísia: "Tunísia",
  Turcomenistão: "Turcomenistão",
  Turquia: "Turquia",
  Tuvalu: "Tuvalu",
  Ucrânia: "Ucrânia",
  Uganda: "Uganda",
  Uruguai: "Uruguai",
  Uzbequistão: "Uzbequistão",
  Vanuatu: "Vanuatu",
  Venezuela: "Venezuela",
  Vietnã: "Vietnã",
  Zâmbia: "Zâmbia",
  Zimbábue: "Zimbábue",
};

export const states = {
  AC: "Acre",
  AL: "Alagoas",
  AP: "Amapá",
  AM: "Amazonas",
  BA: "Bahia",
  CE: "Ceará",
  DF: "Distrito Federal",
  ES: "Espírito Santo",
  GO: "Goiás",
  MA: "Maranhão",
  MT: "Mato Grosso",
  MS: "Mato Grosso do Sul",
  MG: "Minas Gerais",
  PA: "Pará",
  PB: "Paraíba",
  PR: "Paraná",
  PE: "Pernambuco",
  PI: "Piauí",
  RJ: "Rio de Janeiro",
  RN: "Rio Grande do Norte",
  RS: "Rio Grande do Sul",
  RO: "Rondônia",
  RR: "Roraima",
  SC: "Santa Catarina",
  SP: "São Paulo",
  SE: "Sergipe",
  TO: "Tocantins",
};
